In [1]:
import torch 
import numpy as np
from Loss import Loss
from OccamNet import OccamNet
from Trainer import ONTrainer
from cocob import COCOBBackprop 
from bases import *
#nb_elements = 20
#X = np.random.randint(2, size=(nb_elements, 1))
X = [[np.array([i])] for i in range(10)]
Y = [[np.sin(x)+np.cos(x)] for x in range(10)]

In [2]:
model = OccamNet([1], [1], 
                    [[on_sin(), on_cos(), on_sum(), on_sub()], 
                    [on_sin(), on_cos(), on_sum(), on_sub()], 
                    [on_identity()]], 
                    [0.01, 0.01, 0.01], 
                    skip_connections=True, is_none=False)
criterion = Loss(0.01)
optimizer = COCOBBackprop(model.parameters())
trainer = ONTrainer(model, criterion, optimizer)

trained_model = trainer.fit(X, Y, 10, 200)

epoch 0
Parameter containing:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64, requires_grad=True) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)
Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64, requires_grad=True) tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.2685e-44,  4.2685e-44,  4.2685e-44,  4.2685e-44, -1.7074e-43],
        [ 4.2685e-44, -1.7074e-43,  4.2685e-44,  4.2685e-44,  4.2685e-44],
        [ 1.6045e-14,  1.6045e-14,  1.6045e-14,  1.6045e-14, -6.4178e-14],
        [ 1.6045e-14, -6.4178e-14,  1.6045e-14,  1.6045e-14,  1.6045e-14]],
       dtype=torch.float64)
Parameter conta

In [3]:
list(trained_model.parameters())

[Parameter containing:
 tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]], dtype=torch.float64, requires_grad=True),
 Parameter containing:
 tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0238, 0.9762, 0.9762, 0.9762, 0.9762],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], dtype=torch.float64,
        requires_grad=True),
 Parameter containing:
 tensor([[0.9734, 0.9734, 0.9734, 0.9734, 0.9734, 0.9734, 1.0266, 0.9734, 0.9734]],
        dtype=torch.float64, requires_grad=True)]

In [4]:
trained_model.samples_paths_and_probas(3)


([[[<bases.on_identity at 0x16b55f160>, <bases.on_cos at 0x16b55e500>, 0]],
  [[<bases.on_identity at 0x16b55f160>, <bases.on_cos at 0x16b55e500>, 0]],
  [[<bases.on_identity at 0x16b55f160>, <bases.on_cos at 0x16b55e500>, 0]]],
 [[[-1, None], [2, [1]]], [[-1, None], [2, [1]]], [[-1, None], [2, [1]]]],
 [[[6], [0]], [[6], [0]], [[6], [0]]])

In [5]:
import copy
nb_sampled_paths = 1

#X = [x.append(np.array([None])) for x in X]
X = [[copy.deepcopy(x) for _ in range(nb_sampled_paths)] for x in X]
# Reshape Y so that shape == (nb elements, output dim).
Y = torch.tensor(Y, requires_grad = False)

the_paths, the_keys_probas, the_keys_path2 = trained_model.samples_paths_and_probas(nb_sampled_paths)

for x, y in zip(X, Y):
    # This imply to compute the pred of the model for each sampled path
    pred = trained_model.forward(x, the_paths) # shape == (nb sampled paths, output dim)
    print(pred, y)

[[array([1.])]] tensor([1.], dtype=torch.float64)
[[array([0.54030231])]] tensor([1.3818], dtype=torch.float64)
[[array([-0.41614684])]] tensor([0.4932], dtype=torch.float64)
[[array([-0.9899925])]] tensor([-0.8489], dtype=torch.float64)
[[array([-0.65364362])]] tensor([-1.4104], dtype=torch.float64)
[[array([0.28366219])]] tensor([-0.6753], dtype=torch.float64)
[[array([0.96017029])]] tensor([0.6808], dtype=torch.float64)
[[array([0.75390225])]] tensor([1.4109], dtype=torch.float64)
[[array([-0.14550003])]] tensor([0.8439], dtype=torch.float64)
[[array([-0.91113026])]] tensor([-0.4990], dtype=torch.float64)


In [6]:

print([i.item() for i in (trained_model.forward(X, matrix_pathes)[0])])
print(Y[:n].flatten())
the_paths = trained_model.from_matrix_to_paths(matrix_pathes)

print(the_paths)

NameError: name 'matrix_pathes' is not defined

In [ ]:
print(trained_model.forward(X, matrix_pathes)[1])
print(W[:n])

[array([[0.97942554]]), array([[1.80960278]]), array([[2.78122378]]), array([[3.13384322]]), array([[3.14159258]]), array([[3.14159265]]), array([[3.14159265]]), array([[3.14159265]]), array([[3.14159265]]), array([[3.14159265]])]
[[ 0.5       ]
 [ 2.21905355]
 [ 2.83005222]
 [ 0.39782469]
 [ 1.05823839]
 [-1.28434261]
 [-1.26552221]
 [ 5.43726636]
 [18.65648158]
 [31.19831875]]


In [ ]:
trained_model.get_proba_distributions()

[tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]], dtype=torch.float64, grad_fn=<DivBackward0>),
 tensor([[9.8945e-01, 2.8562e-03, 2.2547e-03, 2.4439e-03, 2.9932e-03],
         [2.2664e-02, 2.2664e-02, 9.1303e-01, 2.2664e-02, 1.8977e-02],
         [1.1492e-03, 1.4426e-04, 6.6071e-04, 1.3521e-04, 9.9791e-01],
         [3.0486e-04, 9.9827e-01, 7.6097e-04, 2.4972e-04, 4.1600e-04],
         [2.4436e-01, 5.8841e-02, 2.5953e-02, 2.8099e-02, 6.4275e-01],
         [2.0545e-02, 1.9272e-01, 3.1879e-02, 7.4213e-01, 1.2723e-02]],
        dtype=torch.float64, grad_fn=<DivBackward0>),
 tensor([[6.5641e-05, 9.9028e-01, 6.6673e-05, 5.8555e-05, 5.9294e-05, 1.1141e-03,
          6.7358e-05, 8.2219e-03, 6.2194e-05]], dtype=torch.float64,
        grad_fn=<DivBackward0>)]